#!/bin/sh
set -e

case "$1" in
	remove|purge)
		if command -v systemctl >/dev/null 2>&1; then
			systemctl daemon-reload >/dev/null 2>&1 || true
		fi

		if command -v udevadm >/dev/null 2>&1; then
			udevadm control --reload-rules >/dev/null 2>&1 || true
		fi
		;;
esac

#DEBHELPER#
